default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>


development:
  <<: *default
  database: rails_sidekiq_redis_development

test:
  <<: *default
  database: rails_sidekiq_redis_test

production:
  <<: *default
  database: rails_sidekiq_redis_production
